import type { Metadata } from "next";
import { Inter_Tight } from 'next/font/google';
import "./index.scss";

export const metadata: Metadata = {
  title: "Legaplant To-Do List",
  description: "Generated by create next app",
};

const interTight = Inter_Tight({
  subsets: ['latin'], 
  weight: ['400', '700'], 
  display: 'swap', 
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-br">
      <body className={interTight.className}>
        {children}
      </body>
    </html>
  );
}
